#!/usr/bin/env bash
# Install and configure nginx on a web server

if [ ! -d "/etc/apt" ]; then
	echo "This script only works on Debian-based systems."
	exit 1
fi

sudo apt -y update
sudo apt -y install nginx

sudo service nginx start
sudo ufw allow 'Nginx HTTP'

sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www/html

echo "Hello World!" >/var/www/html/index*.html

sudo service nginx restart
