#!/usr/bin/env bash
# Install and configure nginx on a web server

sudo apt -y update
sudo apt -y install nginx

sudo ufw allow 'Nginx HTTP'

sudo echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    location / {
        return 200 'Hello World!';
    }
}" >/etc/nginx/sites-available/default

if [ "$(grep -R default_server /etc/nginx/sites-enabled/)" ]; then
	echo "More than one default server in Nginx configuration"
	exit 1
fi

sudo nginx -t
sudo systemctl restart nginx
