#!/usr/bin/env bash
# Configure 404 page on an nginx web server

if [ ! -d "/etc/apt" ]; then
	echo "This script only works on Debian-based systems."
	exit 1
fi

sudo apt -y update
sudo apt -y install nginx

sudo service nginx start
sudo ufw allow 'Nginx HTTP'

sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www/html

echo "Ceci n'est pas une page" >/var/www/html/404.html

# Configure Nginx to display a custom 404 page
sudo sed -i '/^\tlocation \/ {/i\ \terror_page 404 /404.html;\n' /etc/nginx/sites-available/default

sudo service nginx restart
