#!/usr/bin/env bash
# Configure an nginx web server with Custom HTTP Response Header

if [ ! -d "/etc/apt" ]; then
	echo "This script is dedicated to ubuntu systems."
	exit 1
fi

sudo apt-get -y update
sudo apt-get -y install nginx

sudo service nginx start
sudo ufw allow 'Nginx HTTP'

sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www/html

sudo sed -i '/^\tlocation \/ {/i\ \tadd_header X-Served-By "$HOSTNAME";\n' /etc/nginx/sites-available/default

sudo service nginx restart
