#!/usr/bin/env bash
# Fix Nginx configuration so it listens on port 80

if [ ! -d "/etc/apt" ]; then
	echo "This script only works on Debian-based systems."
	exit 1
fi

sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
