#!/usr/bin/env bash
# Install and configure nginx on a web server

# Check if running on Ubuntu
if [ ! -d "/etc/apt" ]; then
	echo "This script is dedicated to ubuntu systems."
	exit 1
fi

# Install Nginx if it's not already installed
if ! nginx -v &>/dev/null; then
	sudo apt-get update -y
	sudo apt-get install -y nginx
fi

# Start nginx and allow HTTP
sudo service nginx start
sudo ufw allow 'Nginx HTTP'

# Change ownership and permissions of /var/www/html
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www/html

# Restart nginx
sudo service nginx restart
