#!/usr/bin/env bash
# Bash init script for ./manage_my_process

PID_FILE=/var/run/my_process.pid

start_process() {
	./manage_my_process &
	echo $! >$PID_FILE
}

clean_process() {
	kill "$(cat $PID_FILE)"
	rm -f $PID_FILE
}

if [ "$#" -ne 1 ]; then
	echo "Usage: manage_my_process {start|stop|restart}"
	exit 1
fi

case "$1" in
start)
	start_process
	echo "manage_my_process started"
	;;
stop)
	clean_process
	echo "manage_my_process stopped"
	;;
restart)
	clean_process
	start_process
	echo "manage_my_process restarted"
	;;
*)
	echo "Usage: manage_my_process {start|stop|restart}"
	exit 1
	;;
esac

exit 0
