#!/usr/bin/env bash
# This script parses an Apache log file and displays in descending order occurences of groupings (IP, STATUS_CODE)

awk '{
	counts[$1, $9]++;
	next
} END {
	for (i in counts) {
		split(i, sep, SUBSEP);
		print counts[sep[1], sep[2]], sep[1], sep[2]
	}
}' apache-access.log | sort -gr
