#!/usr/bin/env bash
# This script parses an Apache log file and displays in descending order occurences of groupings (IP, STATUS_CODE)

awk '{
	counts[$1, $9]++;
	next
}' apache-access.log | sort -gr
