#!/usr/bin/env bash
# This script parses an Apache log file and displays in descending order occurences of groupings (IP, STATUS_CODE)

awk '{
	print $1, $9
}' apache-access.log | sort | uniq -c | sort -gr
