#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# For the 9th iteration, displays "Hi" also.

for i in {1..10}
do
	echo "Best School"

	if [ "$i" -eq 9 ]
	then
		echo "Hi"
	fi
done
