#!/usr/bin/env bash
# This script is displaying "Best School" 20 times
# For the 4th iteration, displays "bad luck from China"
# For the 9th iteration, displays "bad luck from Japan"
# For the 17th iteration, displays "bad luck from Italy"


i=1
while [ $i -le 20 ]
do
	echo "$i"
	if [ $i -eq 4 ]
	then
		echo "bad luck from China"
	elif [ $i -eq 9 ]
	then
		echo "bad luck from Japan"
	elif [ $i -eq 17 ]
	then
		echo "bad luck from Italy"
	fi
	i=$(( i+1 ))
done
