#!/bin/bash
# Set up a firewall for web server and forward port 8080 to 80

sudo apt update
sudo apt install ufw -y

sudo ufw default deny incoming
sudo ufw default allow outgoing

sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp

echo "y" | sudo ufw enable

sudo sed -i "s/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/1" /etc/sysctl.conf

sudo sysctl -p

sudo iptables -t nat -A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80
