#!/usr/bin/env bash
# This script checks if a file exists and if it is empty
# The file is named school.

FILE="school"
if [ -e "$FILE" ]; then
   echo "school file exists"
   if [ -s "$FILE" ]; then
       echo "school file is not empty"
   else
       echo "school file is empty"
   fi
   if [ -f "$FILE" ]; then
       echo "school is a regular file"
   fi
else 
   echo "school file does not exist"
fi
